/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * SMTP中继服务API
 * 基于Go+Gin的SMTP转发中继服务API文档
 * OpenAPI spec version: 1.0
 */
import type {
  ApiLoginRequest,
  ApiLoginResponse,
  ApiRegisterRequest,
  ApiRegisterResponse,
} from "./smtpApi.schemas";
import { customAxios } from "../custom-axios";

export const getAuth = () => {
  /**
   * 用户登录获取JWT令牌
   * @summary 用户登录
   */
  const postApiV1AuthLogin = (apiLoginRequest: ApiLoginRequest) => {
    return customAxios<ApiLoginResponse>({
      url: `/api/v1/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiLoginRequest,
    });
  };
  /**
   * 注册新用户账户
   * @summary 用户注册
   */
  const postApiV1AuthRegister = (apiRegisterRequest: ApiRegisterRequest) => {
    return customAxios<ApiRegisterResponse>({
      url: `/api/v1/auth/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiRegisterRequest,
    });
  };
  return { postApiV1AuthLogin, postApiV1AuthRegister };
};
export type PostApiV1AuthLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["postApiV1AuthLogin"]>>
>;
export type PostApiV1AuthRegisterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["postApiV1AuthRegister"]>>
>;
