/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * SMTP中继服务API
 * 基于Go+Gin的SMTP转发中继服务API文档
 * OpenAPI spec version: 1.0
 */
import type {
  ApiAPIResponse,
  ApiCreateCredentialRequest,
  ApiCreateCredentialResponse,
  ApiCredentialListResponse,
  ApiCredentialResponse,
  ApiResetPasswordResponse,
  ApiUpdateCredentialRequest,
} from "./smtpApi.schemas";
import { customAxios } from "../custom-axios";

export const getSmtpCredentials = () => {
  /**
   * 获取当前用户的所有SMTP凭据
   * @summary 获取SMTP凭据列表
   */
  const getApiV1Credentials = () => {
    return customAxios<ApiCredentialListResponse>({
      url: `/api/v1/credentials`,
      method: "GET",
    });
  };
  /**
   * 为当前用户创建新的SMTP凭据
   * @summary 创建SMTP凭据
   */
  const postApiV1Credentials = (
    apiCreateCredentialRequest: ApiCreateCredentialRequest,
  ) => {
    return customAxios<ApiCreateCredentialResponse>({
      url: `/api/v1/credentials`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiCreateCredentialRequest,
    });
  };
  /**
   * 删除指定ID的SMTP凭据
   * @summary 删除SMTP凭据
   */
  const deleteApiV1CredentialsId = (id: string) => {
    return customAxios<ApiAPIResponse>({
      url: `/api/v1/credentials/${id}`,
      method: "DELETE",
    });
  };
  /**
   * 获取指定ID的SMTP凭据详情
   * @summary 获取单个SMTP凭据
   */
  const getApiV1CredentialsId = (id: string) => {
    return customAxios<ApiCredentialResponse>({
      url: `/api/v1/credentials/${id}`,
      method: "GET",
    });
  };
  /**
   * 更新指定ID的SMTP凭据信息
   * @summary 更新SMTP凭据
   */
  const putApiV1CredentialsId = (
    id: string,
    apiUpdateCredentialRequest: ApiUpdateCredentialRequest,
  ) => {
    return customAxios<ApiAPIResponse>({
      url: `/api/v1/credentials/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: apiUpdateCredentialRequest,
    });
  };
  /**
   * 重置指定ID的SMTP凭据密码
   * @summary 重置SMTP凭据密码
   */
  const postApiV1CredentialsIdResetPassword = (id: string) => {
    return customAxios<ApiResetPasswordResponse>({
      url: `/api/v1/credentials/${id}/reset-password`,
      method: "POST",
    });
  };
  return {
    getApiV1Credentials,
    postApiV1Credentials,
    deleteApiV1CredentialsId,
    getApiV1CredentialsId,
    putApiV1CredentialsId,
    postApiV1CredentialsIdResetPassword,
  };
};
export type GetApiV1CredentialsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getSmtpCredentials>["getApiV1Credentials"]>
  >
>;
export type PostApiV1CredentialsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getSmtpCredentials>["postApiV1Credentials"]>
  >
>;
export type DeleteApiV1CredentialsIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSmtpCredentials>["deleteApiV1CredentialsId"]
    >
  >
>;
export type GetApiV1CredentialsIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getSmtpCredentials>["getApiV1CredentialsId"]>
  >
>;
export type PutApiV1CredentialsIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getSmtpCredentials>["putApiV1CredentialsId"]>
  >
>;
export type PostApiV1CredentialsIdResetPasswordResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSmtpCredentials
      >["postApiV1CredentialsIdResetPassword"]
    >
  >
>;
