/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * SMTP中继服务API
 * 基于Go+Gin的SMTP转发中继服务API文档
 * OpenAPI spec version: 1.0
 */
import type {
  ApiQuotaStatsResponse,
  ApiStatsResponse,
} from "./smtpApi.schemas";
import { customAxios } from "../custom-axios";

export const getStatus = () => {
  /**
   * 获取用户邮件统计信息和凭据统计信息
   * @summary 获取统计信息
   */
  const getApiV1Stats = () => {
    return customAxios<ApiStatsResponse>({
      url: `/api/v1/stats`,
      method: "GET",
    });
  };
  /**
   * 获取用户邮件配额使用情况统计
   * @summary 获取配额统计
   */
  const getApiV1StatsQuota = () => {
    return customAxios<ApiQuotaStatsResponse>({
      url: `/api/v1/stats/quota`,
      method: "GET",
    });
  };
  return { getApiV1Stats, getApiV1StatsQuota };
};
export type GetApiV1StatsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getStatus>["getApiV1Stats"]>>
>;
export type GetApiV1StatsQuotaResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getStatus>["getApiV1StatsQuota"]>>
>;
