/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * SMTP中继服务API
 * 基于Go+Gin的SMTP转发中继服务API文档
 * OpenAPI spec version: 1.0
 */
import type { GetHealth200 } from "./smtpApi.schemas";
import { customAxios } from "../custom-axios";

export const getSystem = () => {
  /**
   * 检查服务健康状态
   * @summary 健康检查
   */
  const getHealth = () => {
    return customAxios<GetHealth200>({ url: `/health`, method: "GET" });
  };
  return { getHealth };
};
export type GetHealthResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSystem>["getHealth"]>>
>;
