/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * SMTP中继服务API
 * 基于Go+Gin的SMTP转发中继服务API文档
 * OpenAPI spec version: 1.0
 */
import type {
  ApiAPIResponse,
  ApiUpdateUserInfoRequest,
  ApiUserInfoResponse,
} from "./smtpApi.schemas";
import { customAxios } from "../custom-axios";

export const getUsermgmt = () => {
  /**
   * 获取当前用户的详细信息
   * @summary 获取用户信息
   */
  const getApiV1User = () => {
    return customAxios<ApiUserInfoResponse>({
      url: `/api/v1/user`,
      method: "GET",
    });
  };
  /**
   * 更新当前用户的信息
   * @summary 更新用户信息
   */
  const putApiV1User = (apiUpdateUserInfoRequest: ApiUpdateUserInfoRequest) => {
    return customAxios<ApiAPIResponse>({
      url: `/api/v1/user`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: apiUpdateUserInfoRequest,
    });
  };
  return { getApiV1User, putApiV1User };
};
export type GetApiV1UserResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsermgmt>["getApiV1User"]>>
>;
export type PutApiV1UserResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsermgmt>["putApiV1User"]>>
>;
